### ISSUE TITLE
Cookie expired issue

### ISSUE THREAD

**Issue by sajanchhetri** [HARRY-EXE/HARRYv6#1]
When i run the script and try to login using cookie its says cookie expired and when i try to login with id/pass i says login complete but again its ask for login😑 can you fix it or tell the truble soot way😶

**Comment by Avengersdipak** [comment]
Plz tell me the id/ pass or cookie🙏🙏🙏

**Comment by HARRY-EXE** [comment]
USE DATR COOKIES :)

**Comment by HARRY-EXE** [comment]
> Plz tell me the id/ pass or cookie🙏🙏🙏

YOU CAN YT SEARCH ON HOW TO MAKE FACEBOOK COOKIES :)

**Comment by HARRY-EXE** [comment]
> When i run the script and try to login using cookie its says cookie expired and when i try to login with id/pass i says login complete but again its ask for login😑 can you fix it or tell the truble soot way😶

DUE TO SOME NEW FACEBOOK UPDATES IT HSA BEEN MUCH HARDER FOR US TO GET CORRECT AMOUNT OF INFORMATION USING COOKIES IN SIMPLE LANGUAGE NOWADAYS COOKIES LOGIN IS A HARDER PROCESS TO DO BUT YOU CAN USE DATR COOKIES TO LOG INTO IT ASAP :)
