### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by RexX009** [HARRY-EXE/HARRYv6#2]
Hey i am getting thie error i don't know how to fix can u tell me the solution for this error 
![Screenshot_2023-12-31-09-19-52-711_com termux](https://github.com/HARRY-EXE/HARRYv6/assets/121856787/7c8dae9c-4ad1-4d72-ae11-4924cc0e74a6)

**Comment by HARRY-EXE** [comment]
has been solved sorry for late reply we are currently running v6.9.5 check it out :)
